---
abstract: 'Easily output perl object attributes to an ASCII table'
author:
  - 'Mark Allen <mrallen1@yahoo.com>'
build_requires:
  Carp: 0
  Moose: 0.94
  Test::More: 0
  Tie::IxHash: 0
  namespace::autoclean: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Table-Simple
provides:
  Table::Simple:
    file: lib/Table/Simple.pm
    version: 0.02
  Table::Simple::Column:
    file: lib/Table/Simple/Column.pm
  Table::Simple::Output:
    file: lib/Table/Simple/Output.pm
  Table::Simple::Output::Theory:
    file: lib/Table/Simple/Output/Theory.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
